module.exports = {
    books: [
        {
            _id: '1',
            name: 'Шерлок Холмс',
            author: 'А.К. Дойл',
            pages: 200,
            year: 1999,
            genre: 'Детективы',
            image: '/images/1.jpg',
            price: 199,
            rating: 4.5,
            numReviews: 10,
            countInStock: 6,
        },
        {
            _id: '2',
            name: 'Золотая рыбка',
            author: 'А.С. Пушкин',
            pages: 23,
            year: 1984,
            genre: 'Сказки',
            image: '/images/2.jpg',
            price: 59,
            rating: 4.8,
            numReviews: 8,
            countInStock: 12,
        },
        {
            _id: '3',
            name: 'Война и мир',
            author: 'Л.Н. Толстой',
            pages: 680,
            year: 1995,
            genre: 'Романы',
            image: '/images/3.jpg',
            price: 99,
            rating: 4.6,
            numReviews: 12,
            countInStock: 35,
        },
        {
            _id: '4',
            name: 'Лолита',
            author: 'В.А. Набоков',
            pages: 225,
            year: 2001,
            genre: 'Романы',
            image: '/images/4.jpeg',
            price: 209,
            rating: 3.7,
            numReviews: 4,
            countInStock: 6,
        },
        {
            _id: '5',
            name: 'Человек-невидимка',
            author: 'Р.Л. Эллисон',
            pages: 144,
            year: 1999,
            genre: 'Фантастика',
            image: '/images/5.jpg',
            price: 159,
            rating: 4.6,
            numReviews: 10,
            countInStock: 11,
        },
        {
            _id: '6',
            name: 'На маяк',
            author: 'В.В. Вульф',
            pages: 58,
            year: 1999,
            genre: 'Романы',
            image: '/images/6.jpg',
            price: 99,
            rating: 4.2,
            numReviews: 2,
            countInStock: 3,
        },
    ]
}